apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
  role: opsfleet-dev
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: opsfleet-dev
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: opsfleet-dev
  tags:
    karpenter.sh/discovery: opsfleet-dev